language: android
jdk: oraclejdk8
sudo: false

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-24
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
  licenses:
      - 'android-sdk-preview-license-+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew
script:
 - ./gradlew clean build -PdisablePreDex --continue --stacktrace
env:
 - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
branches:
  only:
    - master