language: android
android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-23
    - extra-android-m2repository
  licenses:
      - 'android-sdk-preview-license-+'
      - 'android-sdk-license-.+'
      - 'google-gdk-license-.+'

before_install:
 - chmod +x gradlew
script:
 - ./gradlew clean build -PdisablePreDex --continue --stacktrace
env:
 - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"
branches:
  only:
    - master